/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './employees.module';
import * as i2 from './add/addEmployee.component.ngfactory';
import * as i3 from '../tasks/tasks.component.ngfactory';
import * as i4 from '@angular/forms';
import * as i5 from '@angular/common';
import * as i6 from '../../errors/error.service';
import * as i7 from '../auth.service';
import * as i8 from '@angular/http';
import * as i9 from './employee.service';
import * as i10 from '@angular/router';
import * as i11 from './add/addEmployee.component';
import * as i12 from '../tasks/tasks.component';
export const EmployeesModuleNgFactory:i0.NgModuleFactory<i1.EmployeesModule> = i0.ɵcmf(i1.EmployeesModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.AddEmployeeComponentNgFactory,i3.TasksComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i4.FormBuilder,i4.FormBuilder,([] as any[])),
          i0.ɵmpd(4608,i4.ɵi,i4.ɵi,([] as any[])),i0.ɵmpd(4608,i5.NgLocalization,i5.NgLocaleLocalization,
              [i0.LOCALE_ID]),i0.ɵmpd(4608,i6.ErrorService,i6.ErrorService,([] as any[])),
          i0.ɵmpd(4608,i7.AuthService,i7.AuthService,[i8.Http,i6.ErrorService]),i0.ɵmpd(4608,
              i9.EmployeeService,i9.EmployeeService,[i8.Http,i6.ErrorService]),i0.ɵmpd(512,
              i4.ɵba,i4.ɵba,([] as any[])),i0.ɵmpd(512,i4.ReactiveFormsModule,i4.ReactiveFormsModule,
              ([] as any[])),i0.ɵmpd(512,i5.CommonModule,i5.CommonModule,([] as any[])),
          i0.ɵmpd(512,i10.RouterModule,i10.RouterModule,[[2,i10.ɵa],[2,i10.Router]]),
          i0.ɵmpd(512,i1.EmployeesModule,i1.EmployeesModule,([] as any[])),i0.ɵmpd(1024,
              i10.ROUTES,() => {
                return [[{path:'',redirectTo:'employees',pathMatch:'full'},{path:'add',
                    component:i11.AddEmployeeComponent},{path:'tasks',component:i12.TasksComponent}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvY3BzdWwvZGVza3RvcC9tZWFuLWFwcC9tZWFuLWFwcC9hc3NldHMvYXBwL2F1dGgvZW1wbG95ZWVzL2VtcGxveWVlcy5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvY3BzdWwvZGVza3RvcC9tZWFuLWFwcC9tZWFuLWFwcC9hc3NldHMvYXBwL2F1dGgvZW1wbG95ZWVzL2VtcGxveWVlcy5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
