/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './employeeList.component.ngfactory';
import * as i2 from './employeeList.component';
import * as i3 from './employee.service';
import * as i4 from './add/addEmployee.component.ngfactory';
import * as i5 from './add/addEmployee.component';
import * as i6 from './employees.component';
const styles_EmployeesComponent:any[] = ([] as any[]);
export const RenderType_EmployeesComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_EmployeesComponent,data:{}});
export function View_EmployeesComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),22,'div',[['class',
      'container-fluid']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),19,'div',[['class','row content'],['style','height: 550px;']],
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
      7,'div',[['class','col-md-4'],['style','height: 100%;']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n            '])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h1',[['style','color: #ffffff;']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['Employees'])),(_l()(),i0.ɵted((null as any),
          ['\n            '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-employee-list',
          ([] as any[]),(null as any),(null as any),(null as any),i1.View_EmployeeListComponent_0,
          i1.RenderType_EmployeeListComponent)),i0.ɵdid(114688,(null as any),0,i2.EmployeeListComponent,
          [i3.EmployeeService],(null as any),(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n        '])),(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),
          i0.ɵeld(0,(null as any),(null as any),7,'div',[['class','col-md-8']],(null as any),
              (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n            '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),4,'div',
          [['class','row'],['style','padding-left: 30px;']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n                '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,
          'app-add-employees',([] as any[]),(null as any),(null as any),(null as any),
          i4.View_AddEmployeeComponent_0,i4.RenderType_AddEmployeeComponent)),i0.ɵdid(114688,
          (null as any),0,i5.AddEmployeeComponent,[i3.EmployeeService],(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n            '])),(_l()(),
          i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵted((null as any),['\n    '])),
      (_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵted((null as any),['\n']))],
      (_ck,_v) => {
        _ck(_v,10,0);
        _ck(_v,18,0);
      },(null as any));
}
export function View_EmployeesComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-employees',
      ([] as any[]),(null as any),(null as any),(null as any),View_EmployeesComponent_0,
      RenderType_EmployeesComponent)),i0.ɵdid(49152,(null as any),0,i6.EmployeesComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const EmployeesComponentNgFactory:i0.ComponentFactory<i6.EmployeesComponent> = i0.ɵccf('app-employees',
    i6.EmployeesComponent,View_EmployeesComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvY3BzdWwvZGVza3RvcC9tZWFuLWFwcC9tZWFuLWFwcC9hc3NldHMvYXBwL2F1dGgvZW1wbG95ZWVzL2VtcGxveWVlcy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvY3BzdWwvZGVza3RvcC9tZWFuLWFwcC9tZWFuLWFwcC9hc3NldHMvYXBwL2F1dGgvZW1wbG95ZWVzL2VtcGxveWVlcy5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9jcHN1bC9kZXNrdG9wL21lYW4tYXBwL21lYW4tYXBwL2Fzc2V0cy9hcHAvYXV0aC9lbXBsb3llZXMvZW1wbG95ZWVzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvY3BzdWwvZGVza3RvcC9tZWFuLWFwcC9tZWFuLWFwcC9hc3NldHMvYXBwL2F1dGgvZW1wbG95ZWVzL2VtcGxveWVlcy5jb21wb25lbnQudHMuRW1wbG95ZWVzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImNvbnRhaW5lci1mbHVpZFwiPlxyXG4gICAgPGRpdiBjbGFzcz1cInJvdyBjb250ZW50XCIgc3R5bGU9XCJoZWlnaHQ6IDU1MHB4O1wiPlxyXG4gICAgICAgIDxkaXYgY2xhc3M9XCJjb2wtbWQtNFwiIHN0eWxlPVwiaGVpZ2h0OiAxMDAlO1wiPlxyXG4gICAgICAgICAgICA8aDEgc3R5bGU9XCJjb2xvcjogI2ZmZmZmZjtcIj5FbXBsb3llZXM8L2gxPlxyXG4gICAgICAgICAgICA8YXBwLWVtcGxveWVlLWxpc3Q+PC9hcHAtZW1wbG95ZWUtbGlzdD5cclxuICAgICAgICA8L2Rpdj5cclxuICAgICAgICA8ZGl2IGNsYXNzPVwiY29sLW1kLThcIj5cclxuICAgICAgICAgICAgPGRpdiBjbGFzcz1cInJvd1wiIHN0eWxlPVwicGFkZGluZy1sZWZ0OiAzMHB4O1wiPlxyXG4gICAgICAgICAgICAgICAgPGFwcC1hZGQtZW1wbG95ZWVzPjwvYXBwLWFkZC1lbXBsb3llZXM+XHJcbiAgICAgICAgICAgIDwvZGl2PlxyXG4gICAgICAgIDwvZGl2PlxyXG4gICAgPC9kaXY+XHJcbjwvZGl2PlxyXG4iLCI8YXBwLWVtcGxveWVlcz48L2FwcC1lbXBsb3llZXM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQUEsZ0JBQTZCLDJDQUN6QjtNQUFBO01BQUEsd0VBQWdEO2FBQUEsZ0NBQzVDO01BQUE7TUFBQSw0Q0FBNEM7TUFDeEM7VUFBQTtNQUE0Qiw4Q0FBYztVQUFBLHFCQUMxQztVQUFBOzZDQUFBLFVBQUE7VUFBQSxrREFBdUM7VUFBQSxpQkFDckMsK0NBQ047aUJBQUE7Y0FBQSwwREFBc0I7VUFBQSxxQkFDbEI7VUFBQTtVQUFBLDRDQUE2QztVQUFBLHlCQUN6QztVQUFBOzJFQUFBLFVBQUE7VUFBQTtVQUFBLGVBQXVDLG1EQUNyQztpQkFBQSxnQ0FDSjtNQUNKLHVDQUNKOztRQVJNO1FBSUk7Ozs7b0JDUmhCO01BQUE7bUNBQUEsVUFBQTtNQUFBOzs7In0=
