/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './auth.module';
import * as i2 from './signup.component.ngfactory';
import * as i3 from './signin.component.ngfactory';
import * as i4 from './logout.component.ngfactory';
import * as i5 from '@angular/forms';
import * as i6 from '@angular/common';
import * as i7 from '@angular/router';
import * as i8 from './signup.component';
import * as i9 from './signin.component';
import * as i10 from './logout.component';
export const AuthModuleNgFactory:i0.NgModuleFactory<i1.AuthModule> = i0.ɵcmf(i1.AuthModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.SignupComponentNgFactory,i3.SigninComponentNgFactory,i4.LogoutComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,i5.FormBuilder,
          i5.FormBuilder,([] as any[])),i0.ɵmpd(4608,i5.ɵi,i5.ɵi,([] as any[])),i0.ɵmpd(4608,
          i6.NgLocalization,i6.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i5.ɵba,
          i5.ɵba,([] as any[])),i0.ɵmpd(512,i5.ReactiveFormsModule,i5.ReactiveFormsModule,
          ([] as any[])),i0.ɵmpd(512,i6.CommonModule,i6.CommonModule,([] as any[])),
          i0.ɵmpd(512,i7.RouterModule,i7.RouterModule,[[2,i7.ɵa],[2,i7.Router]]),i0.ɵmpd(512,
              i1.AuthModule,i1.AuthModule,([] as any[])),i0.ɵmpd(1024,i7.ROUTES,() => {
            return [[{path:'',redirectTo:'signup',pathMatch:'full'},{path:'signup',
                component:i8.SignupComponent},{path:'signin',component:i9.SigninComponent},
                {path:'logout',component:i10.LogoutComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvY3BzdWwvRGVza3RvcC9hbmd1bGFyL21lYW4tYXBwL21lYW4tYXBwL2Fzc2V0cy9hcHAvYXV0aC9hdXRoLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9jcHN1bC9EZXNrdG9wL2FuZ3VsYXIvbWVhbi1hcHAvbWVhbi1hcHAvYXNzZXRzL2FwcC9hdXRoL2F1dGgubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
