/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './task/task.component.ngfactory';
import * as i2 from './task/task.component';
import * as i3 from '../employees/employee.service';
import * as i4 from '@angular/common';
import * as i5 from './taskList.component';
const styles_TaskListComponent:any[] = ([] as any[]);
export const RenderType_TaskListComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_TaskListComponent,data:{}});
function View_TaskListComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-task',([] as any[]),
      (null as any),(null as any),(null as any),i1.View_TaskComponent_0,i1.RenderType_TaskComponent)),
      i0.ɵdid(49152,(null as any),0,i2.TaskComponent,[i3.EmployeeService],{task:[0,
          'task']},(null as any))],(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit;
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
export function View_TaskListComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),4,'div',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n        '])),
      (_l()(),i0.ɵand(16777216,(null as any),(null as any),1,(null as any),View_TaskListComponent_1)),
      i0.ɵdid(802816,(null as any),0,i4.NgForOf,[i0.ViewContainerRef,i0.TemplateRef,
          i0.IterableDiffers],{ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n    '])),(_l()(),i0.ɵted((null as any),['\n']))],(_ck,_v) => {
    var _co:i5.TaskListComponent = _v.component;
    const currVal_0:any = _co.tasks;
    _ck(_v,4,0,currVal_0);
  },(null as any));
}
export function View_TaskListComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-task-list',
      ([] as any[]),(null as any),(null as any),(null as any),View_TaskListComponent_0,
      RenderType_TaskListComponent)),i0.ɵdid(114688,(null as any),0,i5.TaskListComponent,
      [i3.EmployeeService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const TaskListComponentNgFactory:i0.ComponentFactory<i5.TaskListComponent> = i0.ɵccf('app-task-list',
    i5.TaskListComponent,View_TaskListComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvY3BzdWwvZGVza3RvcC9tZWFuLWFwcC9tZWFuLWFwcC9hc3NldHMvYXBwL2F1dGgvdGFza3MvdGFza0xpc3QuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2Nwc3VsL2Rlc2t0b3AvbWVhbi1hcHAvbWVhbi1hcHAvYXNzZXRzL2FwcC9hdXRoL3Rhc2tzL3Rhc2tMaXN0LmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL2Nwc3VsL2Rlc2t0b3AvbWVhbi1hcHAvbWVhbi1hcHAvYXNzZXRzL2FwcC9hdXRoL3Rhc2tzL3Rhc2tMaXN0LmNvbXBvbmVudC50cy5UYXNrTGlzdENvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvY3BzdWwvZGVza3RvcC9tZWFuLWFwcC9tZWFuLWFwcC9hc3NldHMvYXBwL2F1dGgvdGFza3MvdGFza0xpc3QuY29tcG9uZW50LnRzLlRhc2tMaXN0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgPGRpdj5cbiAgICAgICAgPGFwcC10YXNrXG4gICAgICAgICAgICAgICBbdGFza109XCJ0YXNrXCJcbiAgICAgICAgICAgICAgICAqbmdGb3I9XCJsZXQgdGFzayBvZiB0YXNrc1wiPjwvYXBwLXRhc2s+XG4gICAgPC9kaXY+XG4iLCI8YXBwLXRhc2stbGlzdD48L2FwcC10YXNrLWxpc3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0VRO01BQUE7YUFBQTtVQUFBO0lBQ087SUFEUCxXQUNPLFNBRFA7Ozs7b0JBRlIsMkNBQ0k7TUFBQTtNQUFBLDhCQUFLO01BQ0Q7YUFBQTs0QkFBQSx5Q0FFOEM7VUFBQSxhQUM1Qzs7SUFETTtJQUZSLFdBRVEsU0FGUjs7OztvQkNGUjtNQUFBO2tDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
