/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './header.component.ngfactory';
import * as i2 from './header.component';
import * as i3 from './auth/auth.service';
import * as i4 from '@angular/router';
import * as i5 from './errors/error.component.ngfactory';
import * as i6 from './errors/error.component';
import * as i7 from './errors/error.service';
import * as i8 from './app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n'])),(_l()(),i0.ɵeld(1,0,
      (null as any),(null as any),7,'div',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),
      ['\n    '])),(_l()(),i0.ɵeld(3,0,(null as any),(null as any),1,'app-header',
      ([] as any[]),(null as any),(null as any),(null as any),i1.View_HeaderComponent_0,
      i1.RenderType_HeaderComponent)),i0.ɵdid(4,49152,(null as any),0,i2.HeaderComponent,
      [i3.AuthService,i4.Router],(null as any),(null as any)),(_l()(),i0.ɵted(-1,(null as any),
      ['\n    '])),(_l()(),i0.ɵeld(6,16777216,(null as any),(null as any),1,'router-outlet',
      ([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(7,212992,(null as any),0,i4.RouterOutlet,[i4.ChildrenOutletContexts,
          i0.ViewContainerRef,i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],
          (null as any),(null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n'])),(_l()(),
          i0.ɵted(-1,(null as any),['\n'])),(_l()(),i0.ɵeld(10,0,(null as any),(null as any),
          1,'app-error',([] as any[]),(null as any),(null as any),(null as any),i5.View_ErrorComponent_0,
          i5.RenderType_ErrorComponent)),i0.ɵdid(11,114688,(null as any),0,i6.ErrorComponent,
          [i7.ErrorService,i3.AuthService],(null as any),(null as any)),(_l()(),i0.ɵted(-1,
          (null as any),['\n\n'])),(_l()(),i0.ɵted(-1,(null as any),['\n']))],(_ck,
      _v) => {
    _ck(_v,7,0);
    _ck(_v,11,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'my-app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i0.ɵdid(1,49152,(null as any),0,i8.AppComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i8.AppComponent> = i0.ɵccf('my-app',
    i8.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvY3BzdWwvZGVza3RvcC9tZWFuLWFwcC9tZWFuLWFwcC9hc3NldHMvYXBwL2FwcC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvY3BzdWwvZGVza3RvcC9tZWFuLWFwcC9tZWFuLWFwcC9hc3NldHMvYXBwL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9jcHN1bC9kZXNrdG9wL21lYW4tYXBwL21lYW4tYXBwL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvY3BzdWwvZGVza3RvcC9tZWFuLWFwcC9tZWFuLWFwcC9hc3NldHMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPCEtLSA8ZGl2IHN0eWxlPVwiYmFja2dyb3VuZDogbGluZWFyLWdyYWRpZW50KHRvIGJvdHRvbSByaWdodCwgIzAwMWYzZiwgIzAwNWY3Zik7XCI+IC0tPlxyXG48ZGl2PlxyXG4gICAgPGFwcC1oZWFkZXI+PC9hcHAtaGVhZGVyPlxyXG4gICAgPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PlxyXG48L2Rpdj5cclxuPGFwcC1lcnJvcj48L2FwcC1lcnJvcj5cclxuXHJcbjwhLS0gZW5hYmxlcyBodG1sNSB2YWxpZGF0aW9uXHJcbjxmb3JtIG5nTmF0aXZlVmFsaWRhdGU+PC9mb3JtPiAtLT5cclxuIiwiPG15LWFwcD48L215LWFwcD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQXNGLDBDQUN0RjtNQUFBO01BQUEsNENBQUs7TUFBQSxhQUNEO01BQUE7bUNBQUEsVUFBQTtNQUFBLHdEQUF5QjtNQUFBLGFBQ3pCO01BQUE7YUFBQTswREFBQTtVQUFBLDZCQUErQiwwQ0FDN0I7aUJBQUEsMkJBQ047VUFBQTtzQ0FBQSxVQUFBO1VBQUEsOERBQXVCO1VBQUEseUJBR1c7O0lBTDlCO0lBRUo7Ozs7b0JDTEE7TUFBQTthQUFBO1VBQUE7OzsifQ==
