/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './header.component.ngfactory';
import * as i2 from './header.component';
import * as i3 from '@angular/router';
import * as i4 from './errors/error.component.ngfactory';
import * as i5 from './errors/error.component';
import * as i6 from './errors/error.service';
import * as i7 from './app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),9,'div',[['class',
      'container']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'app-header',([] as any[]),(null as any),(null as any),(null as any),i1.View_HeaderComponent_0,
          i1.RenderType_HeaderComponent)),i0.ɵdid(49152,(null as any),0,i2.HeaderComponent,
          ([] as any[]),(null as any),(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),0,'hr',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(16777216,(null as any),
          (null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),i0.ɵdid(212992,(null as any),
          0,i3.RouterOutlet,[i3.ChildrenOutletContexts,i0.ViewContainerRef,i0.ComponentFactoryResolver,
              [8,(null as any)],i0.ChangeDetectorRef],(null as any),(null as any)),
      (_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵted((null as any),['\n'])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-error',([] as any[]),(null as any),
          (null as any),(null as any),i4.View_ErrorComponent_0,i4.RenderType_ErrorComponent)),
      i0.ɵdid(114688,(null as any),0,i5.ErrorComponent,[i6.ErrorService],(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n\n'])),(_l()(),i0.ɵted((null as any),
          ['\n']))],(_ck,_v) => {
    _ck(_v,8,0);
    _ck(_v,12,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'my-app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i0.ɵdid(49152,(null as any),0,i7.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i7.AppComponent> = i0.ɵccf('my-app',
    i7.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvY3BzdWwvZGVza3RvcC9hbmd1bGFyL21lYW4tYXBwL21lYW4tYXBwL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9jcHN1bC9kZXNrdG9wL2FuZ3VsYXIvbWVhbi1hcHAvbWVhbi1hcHAvYXNzZXRzL2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvY3BzdWwvZGVza3RvcC9hbmd1bGFyL21lYW4tYXBwL21lYW4tYXBwL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvY3BzdWwvZGVza3RvcC9hbmd1bGFyL21lYW4tYXBwL21lYW4tYXBwL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XHJcbiAgICA8YXBwLWhlYWRlcj48L2FwcC1oZWFkZXI+XHJcbiAgICA8aHI+XHJcbiAgICA8cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+XHJcbjwvZGl2PlxyXG48YXBwLWVycm9yPjwvYXBwLWVycm9yPlxyXG5cclxuPCEtLSBlbmFibGVzIGh0bWw1IHZhbGlkYXRpb25cclxuPGZvcm0gbmdOYXRpdmVWYWxpZGF0ZT48L2Zvcm0+IC0tPlxyXG4iLCI8bXktYXBwPjwvbXktYXBwPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBdUIsMkNBQ25CO1VBQUE7dUNBQUEsVUFBQTtVQUFBLDJDQUF5QjtVQUFBLGFBQ3pCO1VBQUE7TUFBSSwyQ0FDSjtVQUFBO1VBQUEsbURBQUE7VUFBQTtjQUFBO01BQStCLHVDQUM3QjtNQUNOO1VBQUE7YUFBQTtVQUFBLGVBQXVCLHlDQUdXO1VBQUE7SUFMOUI7SUFFSjs7OztvQkNMQTtNQUFBO2FBQUE7Ozs7In0=
